### ISSUE TITLE
Where is the "real" index.html hosted?

### ISSUE THREAD

**Issue by plowsof** [monerica-project/monerica#129]
An exchange "MajesticBank" listed in the index.html @ https://github.com/monerodice/monerica/blob/487419b43d0b32d774028af2c747b4eb63e14eac/src/index.html#L2180 (but not on the live site) - monerodice.pro for example,  was added to index more recently, and can be seen on the live site.

I have not checked for any other discrepancies. Is this a known issue?

**Comment by monerica-project** [comment]
https://majesticbank.sc was removed because site is offline.

There's no .html page anymore. If you want to see every entity, you'd look at http://monerica.com/api/all or https://monerica.com/submission/findexisting where'd you see the current status. 

There is an audit table to track every change over time.

**Comment by monerica-project** [comment]
Furthermore, it was just added that you can see the audit history for every entity. Keep in mind everything was added this week so it doesn't show anything being added fore that. 

You would go to: https://monerica.com/submission/findexisting then find an entity like: https://monerica.com/submission/submitedit/526 then at the bottom you would see a link to bring you to: https://monerica.com/submission/audit/526  in this example. Here you can see the history for an entity. This would show when something was admitted then later removed. In this example, you see the change of the subcategoryid (it moved from one sub category to another).

This new system is far more organized and every edit is tracked.

**Comment by plowsof** [comment]
for visbility: morphtoken and sideshift removed monero a while ago, and majesticbank.sc is online

**Comment by monerica-project** [comment]
Updated : https://monerica.com/entryaudits/309
