### ISSUE TITLE
[Feature request] Add a section for freelancers workers!

### ISSUE THREAD

**Issue by NotMtth** [monerica-project/monerica#160]
You can understand better if you read  my submission on the website first. 

There is no real section for single people/workers/freelancers to sell their services, putting them under a section with tons of other websites is not really convenient for them.
I'd love to see that!
Thanks for the good work and keep up!

(I could have made a pr but this in C# and I refuse to work on it lol)

**Comment by monerica-project** [comment]
New section added: https://monerica.com/#businesses-software-developers

**Comment by monerica-project** [comment]
A Freelancers section was added: https://monerica.com/#freelancers
