### ISSUE TITLE
[QUESTION] How much do you get for sponsored link?

### ISSUE THREAD

**Issue by inson1** [monerica-project/monerica#179]
I think it would be fair to disclose it.

**Comment by monerica-project** [comment]
It's displayed when you create or renew a listing, example: https://monerica.com/sponsoredlisting/selectduration?id=557

**Comment by inson1** [comment]
Thank you for being transparent!

**Comment by monerica-project** [comment]
There's a dedicated page now: https://monerica.com/sponsoredlisting/offers

**Comment by inson1** [comment]
sorry for spam, I'm just reorganizing my solved issues - jg8tzJHCu0Qcc1zJGcht
