### ISSUE TITLE
Remove Antifawatch

### ISSUE THREAD

**Issue by maltfield** [monerica-project/monerica#185]
This ticket is a request to remove the link to `antifawatch` from the monerica website's section of NGOs titled `Non-Profits`

I was very disappointed today to discover that Monerica is promoting a pro-fascist, homophobic website.

After discovering a link to antifawatch[.]net today on Monerica, I was scrolling through their database and discovered an entry on @micahflee. Note the homophobic slur in the paragraph quoted below (sorry Micah)

 * https://antifawatch[.]net/ViewReport/15d74173

> Micah is a rather prolific actor in the NGO industrial complex and seems to have a rather cozy relationship with Antifa. He works or has worked with numerous groups such as Freedom of the Press Foundation, the Intercept, Distributed Denial of Secrets, and admits to being one of the authors of Unicorn Riot's Discord Leaks platform along with well known Antifa activist Freddy Martinez (another NGO industrial complex actor who has worked with Distributed Denial of Secrets, Unicorn Riot, Freedom of the press foundation, and Lucy Parsons labs). He has a book coming out soon called Hacks, Leaks, and revelations, which is a how-to guide to analyze multiple sets of leaks data and documents. He also writes an article complaining about people on the right doxxing Antifa, which is rather ironic coming from him. His role is generally supporting, proving logistics for Antifa doxxers and laundering their information into the public record through sympathetic journalists, sometimes illegally obtained (see David Capito of Seattle, WA). I guess it does pay to be an Antifa faggot. These guys don't really try to hide the incestuous relationship between Antifa and the NGO industrial complex, however nobody seems to bother to connect the dots.

I think we all know Micah's excellent contributions to privacy tools (Tor, PGP, OnionShare, DangerZone, etc) and how tirelessly he has fought to help educate folks on how to use cryptography tools to protect themselves online.

I truly hope this website was accidentally or automatically added to Monerica. I hope you agree that we should not be promoting fascist or homophobic websites.

Please remove the link to antifawatch from Monerica.

**Comment by monerica-project** [comment]
It was removed.

**Comment by thansk** [comment]
@monerica-project has this project turned political? 

Is there any reason why an anti-violence group that documents (tracks arrests, reports on news using legal and public information) [terrorists](https://www.justice.gov/opa/pr/attorney-general-william-p-barrs-statement-riots-and-domestic-terrorism) shouldn't be included?

**Comment by monerica-project** [comment]
Any group for or against a political cause, or group of people, is a distraction to a circular economy using Monero.

**Comment by thansk** [comment]
> Any group for or against a political cause, or group of people, is a distraction to a circular economy using Monero.

So will you also remove riseup which is a clearly political company?

**Comment by monerica-project** [comment]
Please detail the political affiliation and it can be removed.

**Comment by maltfield** [comment]
I specifically quoted xenophobic and homophobic hate speech from Antifawatch's website, which was attacking a well-respected journalist and member of the privacy community.

I think it's clear that RiseUp is not spreading hate against marginalized folks. In fact, they provide privacy tools *to* marginalized folks.

But, sure, paste here snippets from what you find on Riseup's website..

**Comment by thansk** [comment]
> Please detail the political affiliation and it can be removed.

Even the other person admitted it himself that they provide privacy tools to "marginalized" folks. This is clearly discrimination. It's not an open organization, you can only get an invite by other people already in.

Again, the other person tagged Micah Lee, who is, again, a clearly political person: https://archive.ph/cYPiT

The logo of the company is an using the Antifa colors with stars all over the place.

Even Monerica itself says "social change".

https://web.archive.org/web/20201215090208/https://twitter.com/riseupnet/status/1338771180640215040 ("40 ways to fight fascists" amongst others)

https://web.archive.org/web/20220417110453/https://twitter.com/riseupnet/status/1351632455762137097 - links to various organizations self-described as anarchist such as https://web.archive.org/web/20231203015620/https://kolektiva.media/about/instance "Why we created this instance - anarchy!" and kolektiva itself being an antifa used mastodon instance. Also https://web.archive.org/web/20231206214321/https://sub.media/ ("blocking israel's war machine", "war on anarchists", "the urge to destroy", "the state is a racket", etc.)

Another political post: http://web.archive.org/web/20230223160711/https://twitter.com/riseupnet/status/1216775480713654275 ("you hate capitalism")

I have not included the other connections they have to recently arrested Brian DiPippa as the above should be plenty of evidence.

There is no question about the fact that riseup is a political organization. The question is if you keep the promise of keeping the project Monerica free from political promotions or you decide to take a side.

**Comment by monerica-project** [comment]
It was removed: https://monerica.com/directoryentries/entryaudits/429
