### ISSUE TITLE
Newsletter emails

### ISSUE THREAD

**Issue by monerica-project** [monerica-project/monerica#224]
Have the ability to mass mail everyone in the newsletter. 

- When someone signs up, send an initial email. 
- Have the ability to unsubscribe. 
- Have the ability to save messages to be sent. 
- Have the ability to track who is sent what email.

**Comment by satonotdead** [comment]
Hello, I can suggest (order by priority) a couple of open-source alternatives to implement:

https://github.com/pentacent/keila

https://github.com/knadh/listmonk

Not tried:

https://newsletter.calce.umd.edu/

More complexity:

https://github.com/mautic/mautic

You also need an SMTP server like Mailgun and that's it.

**Comment by monerica-project** [comment]
SendGrid was selected for sending. A custom email newsletter system is already under development, which was added in: https://github.com/monerica-project/monerica/commit/82216170f09aa348cfba9b580b6e35c8ab10cc63

**Comment by satonotdead** [comment]
Okay, so I don't underestand this current issue? May I know if are you OK with contributions or prefer to work completely alone?

Keila do everything you mentioned, I used it and it's reliable. Plus I can help with their implementation or testing, for the Monero community.

**Comment by monerica-project** [comment]
https://github.com/monerica-project/monerica/pull/229
