### ISSUE TITLE
Checkbox for BusKill

### ISSUE THREAD

**Issue by maltfield** [monerica-project/monerica#43]
What do I need to provide as proof to get the green checkbox for BusKill?

## Disclaimer

My name is Michael Altfield, I'm the inventor of BusKill and I run the website https://buskill.in and buskillvampfih2iucxhit3qp36i2zzql3u6pmkeafvlxs3tlmot5yad.onion

I discovered your website when checking referral links. Thanks for listing us :)

 * https://monerica.com/

## Request

I noticed that some sites have a green check emoji next to them = "indicates someone in the community has done a successful test transaction or has used this software/ service", and I'd like to add that checkbox to our name.

Is there any way I can prove that several people in the community have already bought from us over the past year with Monero (and other crypto & fiat currencies?). We sell a few BusKill cables per month, and many of those orders have been made with monero.

I care deeply about the privacy of my users, so I'm not willing to disclose (even privately) unredacted history of our orders, but I'm willing to give redacted screenshots of my WooCommerce store dashboard and/or our CoinPayments account, if that would be acceptable as a valid certification of our authenticity?

You can also see our CoinPayments account page's reviews here, which shows that we're actively processing orders and our demonstrates our trustworthyness.

 * https://www.coinpayments.net/feedback-438efbaef50d2764ab7822669cbf2181

**Comment by maltfield** [comment]
Also, maybe our listing should be moved under the "Technology" section?

**Comment by monerica-project** [comment]
Ok, it's been updated and moved. As far as proof goes, as long as their is some record here of someone approving it or it being witnessed, that is all that can really be done in this context without lots of effort.
