### ISSUE TITLE
Anonymous Locker Category

### ISSUE THREAD

**Issue by itsMikeLowrey** [monerica-project/monerica#47]
I created [Anonymous Locker](https://anonymouslocker.app/). I act as a middleman between amazon and my customers so that they can get items anonymously delivered to amazon lockers near them. I wanted to get a pr going to add my service to your directory, but I am not sure what category would best fit my service. What category should I add my service under?

**Comment by monerica-project** [comment]
It was already added in: https://github.com/monerica-project/monerica/commit/ee585c72bf505eb1117f02047fe7f2fdc035a5d7

It's under Proxies

**Comment by itsMikeLowrey** [comment]
Thank you so much!
