### ISSUE TITLE
KuCoin forces KYC on trading password recovery

### ISSUE THREAD

**Issue by relapser9oQ** [monerica-project/monerica#49]
I would like to note that this exchange forces KYC if you forget your trading password. I would post the following note next to KuCoin for that reasons:

NOTE: This exchange forces KYC if you forget your trading password. The trading password is also required for withdrawals. It is advised to test the trading password and be able to withdraw in forward before depositing any funds.

**Comment by monerica-project** [comment]
https://github.com/monerica-project/monerica/commit/f5d320474a952b9dc5019b797e9ee233b88259f2
