### ISSUE TITLE
Locksmith Direct Southampton

### ISSUE THREAD

**Issue by OllySalanson** [monerica-project/monerica#56]
&#9989; <a href="https://www.locksmith.direct/locksmith-in-southampton">Locksmith Direct Southampton</a> - 24/7 locksmith. 
                Location: Southampton, UK
                <i>
                    Locksmith Direct are your dependable, reliable and trustworthy locksmith on call 24/7 for all your locksmith requirements.
                </i>

**Comment by monerica-project** [comment]
This specific business is already listed (https://www.seymour-locksmiths.co.uk). However, the domain you've provided is different. Is there a reason the URL should be chaired?

**Comment by OllySalanson** [comment]
They are two separate locksmith businesses. Seymour Locksmiths covers the south-east coast of the UK (between Peacehaven and Worthing) and is independently run by Jeffrey Seymour. Locksmith Direct is a new locksmith business run by Jeffrey Seymour and myself, Oliver Salanson. Locksmith Direct has been started to cover the entire UK, first serving Southampton, Winchester and Cambridge, with further areas to be added. Unlike Seymour Locksmiths, Jeffrey will not be carrying out the work directly but instead uses our local locksmith partner in that area whom Jeffrey has vetted. 

I hope this gives an understanding of why we have submitted a listing for both Seymour Locksmiths and Locksmith Direct Southampton as they are both separate companies.

**Comment by monerica-project** [comment]
Ok, thanks for clarifying the service areas.

**Comment by monerica-project** [comment]
added: https://github.com/monerica-project/monerica/commit/bd5acdb709b3ad6cf5c24115a76959d8dc1330c1
