### ISSUE TITLE
Food&drink: add Öz Fıstıkoğlu

### ISSUE THREAD

**Issue by plowsof** [monerica-project/monerica#63]
Öz Fıstıkoğlu  They accept Monero and BCH (and sell, smong other things, Baklava) . 
location: https://www.openstreetmap.org/?mlat=39.98136&mlon=32.80564#map=18/39.98136/32.80564

**Comment by plowsof** [comment]
https://libera.monerologs.net/monero-community/20230424#c240211

an image of the shops window. from a member of the community who visited there / paid in Monero. monero.observer has added it to their resources section using https://www.yemeksepeti.com/restaurant/i0o9/oz-fistikoglu-baklava as a link.

I will confirm the exact payment method - afaik it is 'over the phone' or 'in person' with the shop owner

**Comment by monerica-project** [comment]
If there is an official site the business has which states they accept Monero, then it can be added. It's too difficult to manage and confirm images and map listings. There are tons of random businesses which supposedly accept Monero but if it can't be confirmed from an official source, it's not reliable enough data to be added.

**Comment by sausagenoods** [comment]
They don't have a website. I shopped there and paid with Monero in person. They have "Monero accepted here" stickers next to the front door of the store.

Here is a post on Reddit by the owner himself:
https://www.reddit.com/r/Monero/comments/120pukf/our_turkish_baklava_shop_now_accepts_monero/

The owner can be contacted on Matrix: @horixon:monero.social
He is active on #monero-community:monero.social

Here is another shot of the storefront that has both the Monero accepted here sticker and the store's full name "Oz Fistikoglu"
![image of shop](http://0x0.st/HK4S.jpg)

**Comment by monerica-project** [comment]
Ok, the map link will be their link. Added because there is a confirmation here that someone has successfully done business with them using Monero.
