### ISSUE TITLE
Open links in new tabs?

### ISSUE THREAD

**Issue by tacolopo** [monerica-project/monerica#80]
Idea for site improvement is to change the html links to open in a new tab so people can keep the landing page and explore multiple listings at once. I would be happy to make this change if site admin agrees. I would go through and update each <a> with target="_blank" rel="noopener noreferer".

Current format:
```<a href="https://www.astrology-x-files.com/">Zoidiasoft Technologies</a> - Astrology software for astrologers.```

Proposed change:
```<a href="https://www.astrology-x-files.com/" target="_blank" rel="noopener noreferer">Zoidiasoft Technologies</a> - Astrology software for astrologers.```

**Comment by monerica-project** [comment]
It is simple enough to hold down `ctrl` when clicking links instead of forcing everyone to open a new tab.
