### ISSUE TITLE
Contact Email

### ISSUE THREAD

**Issue by tacolopo** [monerica-project/monerica#82]
Recommendation to site admin to utilize Proton or Tutanota instead of gmail to protect contribution privacy when being contacted.

**Comment by monerica-project** [comment]
It's not advised to use email. Furthermore, paid email services are not within the budget for this project right now.

**Comment by tacolopo** [comment]
@monerica-project I don't see where you disadvise using email:

"The email contact for this project is: [monerican@gmail.com](mailto:monerican@gmail.com)"

ProtonMail and Tutanota both have free options.

**Comment by monerica-project** [comment]
Readme has been updated. 

There was never the intention to list an email address. People started sending emails to a personal account which was never officially listed. As a result, this gmail one was listed to circumvent that. GitHub should be the primary way to make revisions, but accommodating people who don't use it should be possible (twitter preferably).
