### ISSUE TITLE
Lotus Moons Creations & Photography

### ISSUE THREAD

**Issue by shortwavesurfer2009** [monerica-project/monerica#86]
Name: Lotus Moons Creations & Photography
Location: Brunswick, GA, United States
Website: https://lotusmoonscreations.com
Description: Turning moments into memories - portrait photography, outdoor photography, etc. Photo gifts also available
Catagory: unsure, maybe artwork or add a photography section

**Comment by monerica-project** [comment]
Can you please mention on the site that you accept Monero?

**Comment by shortwavesurfer2009** [comment]
> Can you please mention on the site that you accept Monero?

Sure, where would be best? I already sent them the "monero accepted here" thing
![monero-accepted-here-2-2](https://github.com/monerica-project/monerica/assets/116814522/0f681a32-c350-41f2-9824-c64e4d46e263)

**Comment by monerica-project** [comment]
added
